### ISSUE TITLE
Add Cantina Tropicana to After Party

### ISSUE THREAD

**Issue by thanpolas** [skgtech/devit#119]
Add 'Cantina Tropicana' as the venue for the After Party

Use this link as ref:
https://www.facebook.com/pages/Cantina-Tropicana/228214083888307

**Comment by kbariotis** [comment]
Should we add a separate section for this? Or just mention it on the program?

**Comment by thanpolas** [comment]
Mention it in the program most def, and if you feel like it make it a section

**Comment by kbariotis** [comment]
added link at #120

**Comment by varemenos** [comment]
@kbariotis finished this with #120 so I'm closing this issue
