### ISSUE TITLE
masquerade contact emails

### ISSUE THREAD

**Issue by hsoc** [skgtech/devit#145]
Geezus @margaritis :-) that's 101. I am already spammed on this.

John Economou: @hsoc, john@devitconf.org
Kostas Margaritis: @_margaritis, kostas@devitconf.org
DEVit: @devitconf, report@devitconf.org

I suggest john[at]devitconf[dot]org and no linking

**Comment by margaritis** [comment]
Pardon me @hsoc! I thought we live in a polite antispammy world. Probably it was a dream! :smiley:
