### ISSUE TITLE
edit broken link

### ISSUE THREAD

**Issue by ntemposd** [skgtech/devit#163]
"website" link at http://devitconf.org/#venue seems broken.

**Comment by hsoc** [comment]
feedback: Works ok on chrome for linux

**Comment by vkarampinis** [comment]
@ntemposd provide some feedback. OS, Browser?
Tested on osx Chrome/Firefox/Safar works fine.

**Comment by ntemposd** [comment]
I'm on Chrome v: 49.0.2623.87 m and Windows 8.1 - Might be an issue of country(?) 
<img width="956" alt="snip" src="https://cloud.githubusercontent.com/assets/2666341/13880389/aff505e8-ed24-11e5-8382-368ec3fd55bc.PNG">

**Comment by vkarampinis** [comment]
ah! got it! I thought that our link http://devitconf.org/#venue doesnt work.
I'll check later to find the correct url of our venue and fix it. Tnx.
