### ISSUE TITLE
Update bios and add missing links

### ISSUE THREAD

**Issue by margaritis** [skgtech/devit#172]
General guideline: Add current company to all speakers if not included in the bio.

**Laura Kalbag**: 
- Update bio to: Laura is a designer / developer / activist working on social technology that respects human rights. Co-founder of Ind.ie.
- Link to Ind.ie -> https://ind.ie/

**Soledad Penades**: 
- Link to Mozilla -> https://www.mozilla.org/en-US/

**Forbes Lindesay**
- Link to Facebook -> https://www.facebook.com/
- Link to Jade -> http://jade-lang.com/

**Alexandre Morgaut**: 
- Update bio to: Alexandre is a Web Architect and Project manager at Wiztivi. Wakanda community manager & Speaker. Founded NantesJS. Former W3C member.
- Link to Wiztivi -> http://www.wiztivi.com/
- Link to NantesJS -> http://nantesjs.org/

**Etienne Margraff**: 
- Update bio to: Etienne is a web evangelist at Microsoft, MS Ventures Paris CTO and co-creator of Vorlonjs: an OSS cross-platform tool to debug websites and node.js processes.
- Link to Vorlonjs -> http://vorlonjs.io/
- Link to Microsoft Ventures Paris (https://www.microsoftventures.com/locations/paris)
- Link to Microsoft 

**Carlo Sciolla**: 
- Carlo is a travelling technologist passionate with OSS, CTO at Sytac IT Consulting by day and Clojure fanboy by night. He runs the Amsterdam Clojure meetup since 2010.
- Link to Sytac IT Consulting -> http://www.sytac.nl/
- Link to Amsterdam Clojure meetup -> http://www.meetup.com/The-Amsterdam-Clojure-Meetup-Group/ 

**Dan Cuellar**: 
- Change last part of bio: Head of Test Engineering at Shazam Entertainment -> Head of Software Testing at FOODit.
- Link to Appium http://appium.io/
- Link to FOODit -> http://www.foodit.com/

**Karina Popova**:
- Update bio to: Karina is a DevOps/System Software Engineer at whatever mobile incl. international professional interactions with representatives of government institutions & agile companies.
- Add link to whatever mobile -> https://whatevermobile.com/
- Twitter -> https://twitter.com/kary_key

**Hugo Giraudel**: 

-     Update bio to: Hugo is a Front-end developer at Edenspiekermann in Berlin. CSS goblin, Sass hacker & serial writer. OSS toolbelt: SassDoc & Sass Guidelines. Co-author of Jump Start Sass. Net Awards nominee.
- Link to Edenspiekermann -> http://www.edenspiekermann.com/
- Link to Net Awards -> https://thenetawards.com/vote/developer/hugo-giraudel/    
- Link to SassDoc -> http://sassdoc.com/
- Link to Sass Guidelines -> http://sass-guidelin.es/
- Link to Jump Start Sass -> http://howsass.works

**Quentin Adam**: 
- Update bio: Quentin is the founder and CEO of Clever Cloud, a leading European based PaaS hosting platform. Passionate with cloud computing, startups and automation.
- Link to Clever Cloud -> https://www.clever-cloud.com/en/

**Michał Budzyński**:
- Update bio to: Michał is a subway systems geek and ancient Roman coins collector from Poland. Organizer of onGameStart and AntarcticJS. Former Boot2Gecko developer at Mozilla.
- Link to onGameStart -> http://ongamestart.com/
- Link to AntarcticJS -> http://antarcticjs.com/
- Link to Mozilla -> https://www.mozilla.org/en-US/
- Link to Boot2Gecko -> https://wiki.mozilla.org/B2G

**Comment by ntemposd** [comment]
Best commit ever :dart:
