### ISSUE TITLE
Fix main navigation menu in landscape tablet

### ISSUE THREAD

**Issue by modkaffes** [skgtech/devit#179]
Because the *Buy tickets* button is absolutely positioned in the top right and due to the fact that more links were added to the top nav menu, there is some overlapping like this in mid-sized screens:
![screen shot 2016-03-30 at 05 00 04](https://cloud.githubusercontent.com/assets/1829897/14129691/0bfa80ca-f635-11e5-9f35-ab349843ac29.png)

Have to fix.

**Comment by vkarampinis** [comment]
done
