### ISSUE TITLE
(Possibly browsers' bug) In press kit page, clicking in vector logos opens blank page

### ISSUE THREAD

**Issue by modkaffes** [skgtech/devit#181]
When clicking to open the DEVit logo in pdf (vector) in press page, a blank page opens. I'm encountering this in all major browsers in OS X. Possibly it's related to [this bug](https://bugs.chromium.org/p/chromium/issues/detail?id=543018). 

Does anyone have an idea how to fix?

**Comment by ntemposd** [comment]
Works on Windows though

**Comment by vkarampinis** [comment]
It works for me also on osx Chrome.

**Comment by modkaffes** [comment]
Mysteriously, now it works for me, too. I'm closing.
