### ISSUE TITLE
Add auto-invite form for Slack

### ISSUE THREAD

**Issue by ntemposd** [skgtech/devit#191]
We need this to operate exactly the same as the skgtech.io form -> http://skgtech.io/#slack-invite @margaritis is our Slack administrator so ask him for any permissions/access/etc needed. 

Put the form between speakers and the venue sections. 

Tiny form changes:
- Call to action copy changes to "Join our Community on Slack" 
- Slack logo color and "Go" button bg changes to #6aa7cf

**Comment by margaritis** [comment]
We need to setup an identical API Gateway like the one serving SKGTech cause Slack does not allow public exposure of API keys. It acts as a proxy for the Slack API. I can have this tomorrow afternoon.
