### ISSUE TITLE
3 internal links missing

### ISSUE THREAD

**Issue by hsoc** [skgtech/devit#204]
These links  lead to home instead of the intended section. (in latest chrome)

- http://devitconf.org/#workshops
- http://devitconf.org/#caprica
- http://devitconf.org/#endor

**Comment by kbariotis** [comment]
use http://devitconf.org/#sessions @hsoc :)

**Comment by vkarampinis** [comment]
@hsoc can you verify if its ok now? tnx.

**Comment by hsoc** [comment]
@vkarampinis ok on desktop, (not working on android mobile, but it's ok) --closing
