### ISSUE TITLE
URGENT: Workshop works and Top Header Change

### ISSUE THREAD

**Issue by thanpolas** [skgtech/devit#208]
Workshops need to have their own section with a CTA to signup for a workshop (pointing to the google form, ask @ntemposd for the url).

From the top menu we can remove these items: 

* code of conduct
* blog
* press
* engage

And add the new one 'Workshops'

**Comment by thanpolas** [comment]
This is the link to the form: https://docs.google.com/forms/d/1CJOb8RxtE2hSau669_6XpLmo-EADePGdS14_RQmtikg/viewform

**Comment by vkarampinis** [comment]
I think that press and blog should stay on menu cause there is no other way to navigate on those pages.
By removing CoC and Engage we have enough space for Workshops.

**Comment by thanpolas** [comment]
There was a plan to have / create a footer where all these (and more utility) links would be positioned

**Comment by vkarampinis** [comment]
You have right about the footer. We can remove them when the footer is ready. Is this ok?

**Comment by thanpolas** [comment]
yup, go ahead
