### ISSUE TITLE
Build warnings for non-existing file

### ISSUE THREAD

**Issue by toubou91** [skgtech/devit#222]
There are currently some warnings regarding the build:
![image](https://cloud.githubusercontent.com/assets/5684688/16707777/0d8c7498-45db-11e6-8b96-5c19c4cf88f5.png)

It seems, though, that from 8243db21879f9d21b7f729b8b17ac3f08d9eda09 and on, we got rid of  `app/_layouts/single.html`, which means that (possibly) the offending files (image above) are useless, too.

**Comment by vkarampinis** [comment]
tnx @toubou91
