### ISSUE TITLE
Complete the sharing widgets

### ISSUE THREAD

**Issue by thanpolas** [skgtech/devit#23]
Based on the [.psd design](https://docs.google.com/file/d/0B0RK6MvEpwhtdUlJVHVtOTByQ0k/edit) we need to add numbers on the sharing widgets --> http://than.pol.as/Z78e

@kbariotis shared a few helpful urls on codepen, [this one will help you with the numbers](http://codepen.io/andreasstorm/pen/iefKk)

**Comment by kbariotis** [comment]
Done
