### ISSUE TITLE
Add a speaker section 

### ISSUE THREAD

**Issue by ppapapetrou76** [skgtech/devit#24]
We already have our first verified speaker so we need to create a speaker section. I will provide image and bio info of the first speaker.

**Comment by thanpolas** [comment]
Bio + Photo for Mathias: http://lanyrd.com/profile/mathias/bio/

**Comment by thanpolas** [comment]
Bio + Photo for Chris: http://christianheilmann.com/cheatsheet.html

@ppapapetrou76 let us know where to find bio and pic for your speaker asap please.

**Comment by ppapapetrou76** [comment]
Here's the bio for Dr.Heinz Kabutz

"
Heinz is the mastermind behind The Java Specialists' Newsletter. He has a PhD in Computer Science. Heinz has programmed significant portions of several large Java applications and has taught Java to thousands of professional programmers. He is a regular speaker at all the major Java conferences.

Heinz was chosen as a Java Champion by Sun Microsystems, the inventors of Java, for his work in advancing Java.

Heinz presents our Java training courses anywhere in the world, either in person or via remote teaching technologies. He is the author of all our courses, including Java Specialist Master, Design Patterns and Concurrency Specialist Courses.

Despite the name and looks, Heinz is Greek."

Picture here : https://drive.google.com/open?id=0B2qyhdkUvKX-XzIyUVgyUHJleG5rQVVHMlhuTUMyZ1RTMkxN&authuser=0

**Comment by kmargaritis** [comment]
Our?
