### ISSUE TITLE
Use Theme component for Tickets

### ISSUE THREAD

**Issue by thanpolas** [skgtech/devit#29]
Use the markup provided by our theme (http://than.pol.as/ZN5W) for the tickets section.

Links should point to corresponding packages to eventzilla.

Make the last plan (Normal Ticket) disabled

**Comment by kbariotis** [comment]
* What are the corresponding offerings(Entrance, Coffee break, Certificates) of Devit?
* What are the links of the corresponding packages on eventzilla?

**Comment by ppapapetrou76** [comment]
We offer : Entrance , Coffee breaks, Lunch 
Packages : Early bird (40EUR), Normal (50EUR)

**Comment by kbariotis** [comment]
closing via #56
