### ISSUE TITLE
Add current copyright date in the footer

### ISSUE THREAD

**Issue by modkaffes** [skgtech/devit#30]
I think it's proper to have the current date as a copyright notice in the footer section. Furthermore this should be done in a future proof way (eg. via javascript Date()).

See http://updateyourfooter.com

What style do you prefer?:
a) &copy; 2014-2015, or
b) &copy; 2015

**Comment by ppapapetrou76** [comment]
b) © 2015

Patroklos Papapetrou

SoftwareGarden.io

Linkedin <http://www.linkedin.com/in/ppapapetrou> | Twitter
<http://twitter.com/ppapapetrou76> | *Author
<http://softwaregarden.io/my-books> *| Speaker
<http://lanyrd.com/profile/ppapapetrou/> | Blog <http://softwaregarden.io>
 | Google+ <https://plus.google.com/+PatroklosPapapetrou> | GitHub
<https://github.com/ppapapetrou76> |

**Comment by thanpolas** [comment]
PR motherfucker!

On Thursday, January 22, 2015, Papapetrou Patroklos <
notifications@github.com> wrote:

> b) © 2015
>
> Patroklos Papapetrou
>
> SoftwareGarden.io
>
> Linkedin <http://www.linkedin.com/in/ppapapetrou> | Twitter
> <http://twitter.com/ppapapetrou76> | *Author
> <http://softwaregarden.io/my-books> *| Speaker
> <http://lanyrd.com/profile/ppapapetrou/> | Blog <http://softwaregarden.io>
>
> | Google+ <https://plus.google.com/+PatroklosPapapetrou> | GitHub
> <https://github.com/ppapapetrou76> |
>
>
>
> On Thu, Jan 22, 2015 at 10:51 PM, Mod Kaffes <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
>
> > I think it's proper to have the current date as a copyright notice in
> the
> > footer section. Furthermore this should be done in a future proof way
> (eg.
> > via javascript Date()).
> >
> > See http://updateyourfooter.com
> >
> > What style do you prefer?:
> > a) © 2014-2015, or
> > b) © 2015
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/skgtech/devit/issues/30>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/skgtech/devit/issues/30#issuecomment-71096335>.
>


-- 
---
Thanasis Polychronakis

http://thanpol.as

**Comment by modkaffes** [comment]
@thanpolas see #31
