### ISSUE TITLE
DEVit event day app

### ISSUE THREAD

**Issue by kbariotis** [skgtech/devit#305]
This year we would like to have a web/mobile/hybrid (you name it) app for the event day for attendees to:

* View the schedule
* View talks/speakers information
* Rate a talk

We have already some mockups ready so we need to implement them. This issue will keep track of such implementation.

Feel free to suggest an idea or an implementation strategy.

**Comment by kbariotis** [comment]
@modkaffes @modkaffes @vkarampinis @varemenos will you help with styling the app? I've done some work with the basic structure, now we need to style 3-4 mobile pages.

There is also the matter of the backend server that will hold the ratings.

**Comment by modkaffes** [comment]
@kbariotis, sure! Can you link to the mockups?

**Comment by kbariotis** [comment]
https://drive.google.com/file/d/0B0PODvhXDdo7dzA4V3VxLWZwclk/view?usp=sharing

Let's focus on the first screen for now. The Schedule, the Talk info and the Speaker info screens.

**Comment by modkaffes** [comment]
I'm starting the Schedule view.
