### ISSUE TITLE
Fix share count abbreviation

### ISSUE THREAD

**Issue by modkaffes** [skgtech/devit#34]
There's a logical error in [devit-custom-js](https://github.com/skgtech/devit/blob/f1aba09437863403965c8ed4b1b32f5860a5c6d2/app/js/devit-custom.js#29) (line 29) _getK function. 

This function is supposed to abbreviate the share count showing for example '4k' instead of 4000. The problem is that the way it's implemented right now it will only take the first digit of the number returned by social media APIs if it's bigger than 1000 and show it appended by a 'k' char. So for example 15000 shares shows as 1k shares. Wrong!

This should be fixed (I'm all about future-proof, heh) in case the shares surpass the four digit hit count, unless we don't expect that many shares :D

**Comment by kbariotis** [comment]
This is right @modkaffes, cause when i wrote it, i didn't care for numbers above 9999. 
I am not sure how many shares we expect, but we have time until that number. 

If you would like to refactor the function, go ahead.

**Comment by modkaffes** [comment]
Ofc. Assign me please.
