### ISSUE TITLE
Code of Conduct 

### ISSUE THREAD

**Issue by varemenos** [skgtech/devit#36]
Every serious conference has one and every conference should have one.I think it's time we've added one, don't you think?

**Comment by kmargaritis** [comment]
:+1:

**Comment by thanpolas** [comment]
Who can work on it?

**Comment by sirodoht** [comment]
I can work on it if no one else is available, but I can start after Feb 4.

**Comment by varemenos** [comment]
Αρκετά conferences που έχω πετύχει, έχουν σαν reference [αυτό](http://confcodeofconduct.com/)

**Comment by thanpolas** [comment]
:+1:
