### ISSUE TITLE
Add Nicolas Frankel as a speaker

### ISSUE THREAD

**Issue by ppapapetrou76** [skgtech/devit#37]
Bio :"Nicolas Fränkel is a Software Architect with +12 years experience in consulting for many different customers, in a wide range of contexts (such as telecoms, banking, insurances, large retail and public sector). He's generally focused on Java and JavaEE technologies, but he's narrowed interests like Software Quality, Build Processes and Rich Internet Applications. I'm currently working for a eCommerce solution vendor leader. He also double as a teacher in universities and higher education schools, and a trainer for experienced pros, and triples as a book author."

Image : https://pbs.twimg.com/profile_images/468037877280935937/BmolnEdZ.jpeg

**Comment by ppapapetrou76** [comment]
Any idea when we can have it ready?
We need to add speaker details this week ...

**Comment by varemenos** [comment]
@ppapapetrou76 the bio is kinda too long

**Comment by kbariotis** [comment]
@varemenos Use something like this "Nicolas Fränkel is focused on Java and JavaEE technologies, but he's narrowed interests like Software Quality, Build Processes and Rich Internet Applications.".

Also make sure that is dropped on the same line with the others, before we start making hacks for same height. :P

**Comment by ppapapetrou76** [comment]
+1
But shouldn't we display a more complete profile for each speaker? two
lines are not enough.

**Comment by thanpolas** [comment]
> But shouldn't we display a more complete profile for each speaker?

no, less is more. If visitor wants to learn more about a specific speaker they can follow the links we provide

**Comment by varemenos** [comment]
Ok, I've shortened the biography with the text @kbariotis provided
