### ISSUE TITLE
Better hero pictures

### ISSUE THREAD

**Issue by varemenos** [skgtech/devit#43]
We should probably use different pictures for the hero page.

One of the suggestions was for the first one to be of the concert hall

**Comment by georgiats** [comment]
Totally agree!!

**Comment by attheodo** [comment]
+1

**Comment by kbariotis** [comment]
+1

**Comment by kbariotis** [comment]
where can we find some nice pictures of the Concert Hall? It's [website](http://www.tch.gr/default.aspx?lang=el-GR&page=11) has some but low res. Should we contact them?

And also some pictures from Frontmass & Together events?

**Comment by varemenos** [comment]
New hero images are in #64, I'm closing this in favor of the other issue that contains a link to the images
