### ISSUE TITLE
Add a sessions section

### ISSUE THREAD

**Issue by ppapapetrou76** [skgtech/devit#45]
We already know the talks / sessions from the CFP speakers. We should add a program section. This is very critical to attract more participants.

**Comment by ppapapetrou76** [comment]
Actually the correct title should be "Sessions section" . I modified it accordingly. I would like to see something like this : http://oredev.org/2014/sessions or something that will show the available tracks and visitors can filter based on the track. 

Here https://docs.google.com/spreadsheets/d/1RGYC56RvjrbjxFDilKhstzK9T9LiYlsQ_aCGC-ODU3A/edit#gid=0 you can find the sessions we already know the title and description. We can add them

**Comment by kbariotis** [comment]
Ok here is a preview. Some talks' titles and description are missing. 

Titles are required so could you please give me the missing ones? Descriptions are optional but we should either add to all of them or none. So far i've found only one description.

![devitschedule](https://cloud.githubusercontent.com/assets/605742/6212983/a3b6681c-b5f3-11e4-9f5e-bbe688d8c6a9.gif)

**Comment by thanpolas** [comment]
Add icon on break / lunch items?

**Comment by thanpolas** [comment]
@kbariotis what's the branch for this?

**Comment by kbariotis** [comment]
@thanpolas it's https://github.com/skgtech/devit/tree/schedule

**Comment by ppapapetrou76** [comment]
Please find the latest program here : https://docs.google.com/spreadsheets/d/1QjEdeAhj8KUrSUxUFu6YD7kvBhTu55ZT6ddPyVQURgg/edit#gid=0 Let's change also the headers of the two tracks to "SpaceBalls" and "FairLight"

**Comment by thanpolas** [comment]
haha love the names!


---
Thanasis Polychronakis

http://thanpol.as/

**Comment by kbariotis** [comment]
Closing through https://github.com/skgtech/devit/pull/67
