### ISSUE TITLE
Add Forbes Lindsey as a speaker

### ISSUE THREAD

**Issue by ppapapetrou76** [skgtech/devit#46]
Twitter Handle : ForbesLindesay
GitHub : https://github.com/ForbesLindesay/
Bio : I'm a node.js developer who maintains a number of open source projects such as:

  * Jade - a popular JavaScript based templating language for generating dynamic html
  * browserify-middleware - a library to make it easy to host modular JavaScript using CommonJS modules.
  * github-basic - a really simple GitHub client written in JavaScript

I also maintain a number of open source websites providing information about JavaScript:

  * www.promisejs.org
  * esdiscuss.org
  * readable-email.org

I'm enthusiastic about open source, and love the ease with which JavaScript lets you get things done.

**Comment by varemenos** [comment]
could you provide a picture of Forbes? (didn't he provide any)

**Comment by ppapapetrou76** [comment]
Please use the one in his twitter handle
​We will ask him to verify after that.​

**Comment by varemenos** [comment]
I'm closing this issue since the branch was merged. Let me know if you want to keep it open for some reason

**Comment by ppapapetrou76** [comment]
My bad :(
His name is Forbes Lindesay
Can we please fix it on the web site?

**Comment by ppapapetrou76** [comment]
Still wrong . It's Lindesay not Lindesey

**Comment by thanpolas** [comment]
lol, ok ok fixed
