### ISSUE TITLE
Add two more speakers on the website

### ISSUE THREAD

**Issue by thanpolas** [skgtech/devit#52]
## Nikos Zinas

Find photo and bio from [FrontMASS speakers](http://frontmass.org/)

## Nick Krassas

**Image** https://pbs.twimg.com/profile_images/378800000778910841/25de010c698cacd622c07998dffa4f2c.jpeg

**Bio** Nicolas Krassas CISSP is a security researcher passionate with all things security and system administration, he wakes up on CVEs for breakfast and finishes the day filling his twitter stream with all kinds of latest, up to date security related news!

**Comment by varemenos** [comment]
Does Nicolas Krassas has a github? I can't seem to find it

**Comment by thanpolas** [comment]
here it is, but not very strong: https://github.com/dinosn

**Comment by varemenos** [comment]
I guess I'm not including it then
