### ISSUE TITLE
Add Benny Weingarten-Gabbay as speaker

### ISSUE THREAD

**Issue by kmargaritis** [skgtech/devit#54]
* **Twitter Handle** : gardenofwine
* **GitHub** : https://github.com/gardenofwine
* **Bio** : Benny Weingarten-Gabbay is a senior software engineer at ebay, with 15 years of experience from building games at EA, to creating open government mobile apps. Benny is a creative thinker and builder, an improvisation actor, and an activist.

* **Picture** : https://www.dropbox.com/s/unp3e8tt6hopo1v/round%20profile.png?dl=0

**Comment by varemenos** [comment]
Tough surname, hard to include anything useful in the description
