### ISSUE TITLE
Change Benny's name

### ISSUE THREAD

**Issue by kmargaritis** [skgtech/devit#58]
We should change the name from Benny Gabbay to Benny Weingarten.

**Comment by kbariotis** [comment]
Searching for [Benny Gabbay Weingarten](https://www.google.gr/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=benny%20gabbay%20weingarten), first result is LinkedIn with profile name Benny Gabbay. That's why i put it this way.

What's the correct one?

**Comment by varemenos** [comment]
He uses "Benny Weingarten" on twitter

**Comment by kmargaritis** [comment]
No worries Kostas! Just use Benny Weingarten.

**Comment by kbariotis** [comment]
:+1:

**Comment by kbariotis** [comment]
This must be "Benny Gabbay-Weingarten".
