### ISSUE TITLE
Add a sponsors section

### ISSUE THREAD

**Issue by ppapapetrou76** [skgtech/devit#62]
Can we please add a sponsors section?
We should add OTS ( http://www.ots.gr ) as Premium , Trasys (http://www.trasys.be/)  as Standard and Municipality of Thessaloniki

Here are the logos for OTS and Trasys https://drive.google.com/drive/#folders/0B68iSVdp87MFWlZBdFdqYjRNWHM/0B68iSVdp87MFflo2SUMzMXEtTHBmSVlDTXhaWWlpalZwX0hMd2kwcXZGeUdsMHVaMmEtckk

and here is the Mun. Of Thes logo : https://drive.google.com/drive/u/0/#folders/0B68iSVdp87MFOVJEN0lWMTlLXzQ/0B68iSVdp87MFLXZXVC1YTWVUZzg/0B68iSVdp87MFWlZBdFdqYjRNWHM/0B8F6j7sejj7ybmNmNjJzTWtiYTA/0B68iSVdp87MFY25wYWJ0bzE3QzQ

**Comment by kbariotis** [comment]
Closing through https://github.com/skgtech/devit/pull/68
