### ISSUE TITLE
Change the hero images

### ISSUE THREAD

**Issue by ppapapetrou76** [skgtech/devit#64]
Please change the hero images. Find the new ones here : https://drive.google.com/drive/#folders/0B68iSVdp87MFWlZBdFdqYjRNWHM/0B8F6j7sejj7ybmNmNjJzTWtiYTA/0B2qyhdkUvKX-fi1yLThRNzl6VmxsOHd6bUNma1hhYnBEcWVZenNfMUtsdVhucHN3eTRacEk

**Comment by kbariotis** [comment]
Closing this through https://github.com/skgtech/devit/pull/65
