### ISSUE TITLE
Add Jeffrey Nickoloff as our speaker

### ISSUE THREAD

**Issue by ppapapetrou76** [skgtech/devit#73]
Bio: Jeff is currently writing Docker in Action and has a passion for microservices and web development. 
Talk Title: An Introduction to Docker
Abstract: Join us to learn how Docker provided packaging and process isolation has changed the way people build, test, ship, and deploy software.
Image : https://drive.google.com/drive/#folders/0B68iSVdp87MFWlZBdFdqYjRNWHM/0B68iSVdp87MFeUdFOW1jQ2RjZ0E
Twitter : allingeek 
Github : https://github.com/allingeek

**Comment by kbariotis** [comment]
closed through #76
