### ISSUE TITLE
Down arrow alignment

### ISSUE THREAD

**Issue by kmargaritis** [skgtech/devit#79]
Down arrow is not properly aligned in Coffee break and Lunch break in both sections.

![Session section](https://dl.dropboxusercontent.com/u/33885016/down_arrow.png)

**Comment by kbariotis** [comment]
Not sure about the alignments, but those shouldn't be there at all. Related to #71.

**Comment by kmargaritis** [comment]
Yeap Kostas, they should probably not exist at all.. They have no practical use

**Comment by kbariotis** [comment]
Closing  through https://github.com/skgtech/devit/commit/6ccb240a10422f8cb66941cf201b7b90a6cce2ff
