### ISSUE TITLE
Add Hashtag to site

### ISSUE THREAD

**Issue by thanpolas** [skgtech/devit#87]
Add the hashtag, somehow =)

```
#devitconf
```

**Comment by kbariotis** [comment]
![screen shot 2015-04-03 at 10 33 32 pm](https://cloud.githubusercontent.com/assets/605742/6987604/89e9bea2-da51-11e4-891b-f36cf6944596.png)

What do you think @thanpolas ?

**Comment by thanpolas** [comment]
I think a dedicated section would do it more justice

# The Hashtag

> #devitconf
