### ISSUE TITLE
Please add city college as standard sponsor

### ISSUE THREAD

**Issue by ppapapetrou76** [skgtech/devit#90]
Logo here : https://drive.google.com/drive/#folders/0B68iSVdp87MFWlZBdFdqYjRNWHM/0B68iSVdp87MFflo2SUMzMXEtTHBmSVlDTXhaWWlpalZwX0hMd2kwcXZGeUdsMHVaMmEtckk/0B68iSVdp87MFNW1UWGFVMUs0NEk/0B0RK6MvEpwhtaC01ZnBDSnotZnc

URL : http://citycollege.sheffield.eu/

**Comment by kbariotis** [comment]
@ppapapetrou76 The provided logo is too small. Can we have a better version?

**Comment by ppapapetrou76** [comment]
I guess we can.... if we use the existing one will look ugly in the site? I think they use the same on their web site

**Comment by kbariotis** [comment]
Well it's kind of ugly. We shouldn't skip it. Is it hard to get one?
